---
title: "Tomo Guitar Wisdom Updates"
output:
  html_document:
    df_print: paged
---


```{r mylibraries, include = FALSE}
library(xsitemap)
library(tidyverse)
library(clipr)
library(DT)
library(lubridate)
```


```{r getdata, include=FALSE}
x <- xsitemapGet("https://tomovhxtv.vhx.tv/sitemap.xml")%>% 
  slice(10:n() ) %>% 
  mutate(my.basename  = str_remove(loc, "https://tomovhxtv.vhx.tv/")) %>% 
  separate(my.basename,
           into=c("series", "trashme", "title"),
           sep="/") %>% 
  mutate(title = str_replace_na(title, "landing.page") ) %>% 
  # sortingid
  group_by(series) %>% mutate(series.sort.id = row_number() ) %>% ungroup() %>% 
  # updated
  mutate(year =  as.integer(format(lastmod, " %Y")),
         month = as.integer(format(lastmod, "%m")),
         day =  lastmod ) %>% 
  # Make hyperlink Live #
  mutate( 
          title = paste0("<a href = ",'"', loc, '">',title, "</a>") ) %>%
  # datemath
  select(id = series.sort.id,
         year, month, day,
         series = series,
         title) 

```


```{r dataupdatetable, include=FALSE}
x.last.30.days <-
  xsitemapGet("https://tomovhxtv.vhx.tv/sitemap.xml")%>% 
  slice(10:n() ) %>% 
  mutate(my.basename  = str_remove(loc, "https://tomovhxtv.vhx.tv/")) %>% 
  separate(my.basename,
           into=c("series", "trashme", "title"),
           sep="/") %>% 
  mutate(title = str_replace_na(title, "landing.page") ) %>% 
  # sortingid
  group_by(series) %>% mutate(series.sort.id = row_number() ) %>% ungroup() %>% 
  # Dating
  mutate(date.math = as.integer(interval(lastmod, Sys.Date() ) %/% days() )) %>%
  filter(date.math<31) %>% 
  # Make hyperlink Live #
  mutate( 
          title = paste0("<a href = ",'"', loc, '">',title, "</a>") ) %>%
#Selection
  select(id = series.sort.id,
         updated = lastmod,
         days = date.math,
         series = series,
         title) 
```

# Last 30 Days
```{r printlast30days, echo=FALSE, warning=FALSE, message = FALSE}
x.last.30.days %>% 
 filter(!(series %in% "forums")) %>% 
 datatable(filter = 'top', 
            rownames=FALSE,
            extensions = 'FixedColumns',
            options = list(
              columnDefs = list(list(width = '5%',
                                     targets = c(0,1,2) ) ),
              columnDefs = list(list(width = '32%',
                                     targets = c( 3,4) ) ),
                            columnDefs = list(list(width = '50%',
                                     targets = c( 5) ) ),
              fixedColumns = TRUE,
              pageLength = 1000, 
              autoWidth = TRUE),
              escape = FALSE,
              )
```

# Main Table
```{r print.main.data.table, echo=FALSE, warning=FALSE, message = FALSE}
x %>% 
  filter(!(series %in% "forums")) %>% 
  ## Tableformatting ##
  datatable(filter = 'top', 
            rownames=FALSE,
            extensions = 'FixedColumns',
            options = list(
              columnDefs = list(list(width = '5%',
                                     targets = c(0,1,2,3) ) ),
              columnDefs = list(list(width = '30%',
                                     targets = c( 5) ) ),
                            columnDefs = list(list(width = '55%',
                                     targets = c( 6) ) ),
              fixedColumns = TRUE,
              pageLength = 1000, 
              autoWidth = TRUE),
              escape = FALSE,
              )
```



